name=StageConnect
version=1.0.0
author=Chris Noeding <christian@noeding-online.de>, YetAnotherElectronicsChannel <yetanotherelectronicschannel@gmail.com>
maintainer=Chris Noeding <christian@noeding-online.de>, YetAnotherElectronicsChannel <yetanotherelectronicschannel@gmail.com>
sentence=Arduino library for Behringers StageConnect based on A2B
paragraph=Support for StageConnect (A2B) as Master and Slave
category=Communication
url=https://github.com/xn--nding-jua/StageConnect
architectures=*
